### ISSUE TITLE
Review Calculations

### ISSUE THREAD

**Issue by alphonsederus2** [kpwhri/HCSRNCensusDemogACS#4]
I'd like someone that isn't me to review the calculations to confirm that I got them right. :D

**Comment by mhossai22** [comment]
Hi Al! I got a chance to review the calculations and here is what I found: 

- Comment at start of code = variable calculations include income, poverty, education, etc. variables instead of only education. 

** Education variable calculations; (comment at the start of code)

- POV Variables = sum not needed within divide statement since there is only one value to divide by

%let POV_LT_50 = POV_LT_50 = divide(sum(B17026_002E),B17026_001E);   
%let POV_50_74 = POV_50_74 = divide(sum(B17026_003E),B17026_001E);
%let POV_75_99 = POV_75_99 = divide(sum(B17026_004E),B17026_001E); 
%let POV_100_124 = POV_100_124 = divide(sum(B17026_005E),B17026_001E); 
%let POV_125_149 = POV_125_149 = divide(sum(B17026_006E),B17026_001E); 
%let POV_150_174 = POV_150_174 = divide(sum(B17026_007E),B17026_001E);
%let POV_175_184 = POV_175_184 = divide(sum(B17026_008E),B17026_001E); 
%let POV_185_199 = POV_185_199 = divide(sum(B17026_009E),B17026_001E);

- DISABILITY Variable = values should start with 'C18101' instead of 'C18108'

%let DISABILITY = DISABILITY = divide(sum(C18108_007E,C18108_010E,C18108_017E,C18108_020E),sum(C18108_006E,C18108_009E,C18108_016E,C18108_019E)); 

- MGR MALE Variable = VDW Data Dictionary lists C24040_019E first then C24040_018E (will not make a difference in the sum but I just thought you should be aware since all of the other variables followed the same order as the VDW Data Dictionary)

%let MGR_MALE = MGR_MALE = divide(sum(C24040_018E,C24040_019E),C24040_001E);

Let me know if you have questions!

Take Care, 

Muniza

**Comment by alphonsederus2** [comment]
Good eye all around! 
1. I'll remove extraneous sum calls
2. The disability variable would have created a broken variable. Thank you!
3. I will actually update the dictionary at some point!

**Comment by mhossai22** [comment]
Thank you! Glad I could help!

**Comment by alphonsederus2** [comment]
It turns out C18101 does not exist in the API, so C18108 is correct group. But the variables in the group are also incorrect. 

%let DISABILITY = DISABILITY = divide(sum(C18108_007E,C18108_008E,C18108_011E,C18108_012E),C18108_001E);

Numerator
07 - "Estimate!!Total:!!18 to 64 years:!!With one type of disability"
+ 08 - "Estimate!!Total:!!18 to 64 years:!!With two or more types of disability"
+ 11 - "Estimate!!Total:!!65 years and over:!!With one type of disability"
+ 12 - "Estimate!!Total:!!65 years and over:!!With two or more types of disability"

Denominator
01 - "Estimate!!Total:"

English version is "the total number of people with one or more disabilities over the age of 18", which should align with the VDW specification:

> Proportion of people over age 18 living with any disability

Variable refs for 2020
https://api.census.gov/data/2020/acs/acs5/variables/C18108_007E.json
https://api.census.gov/data/2020/acs/acs5/variables/C18108_008E.json
https://api.census.gov/data/2020/acs/acs5/variables/C18108_011E.json
https://api.census.gov/data/2020/acs/acs5/variables/C18108_012E.json
https://api.census.gov/data/2020/acs/acs5/variables/C18108_001E.json
